(** %\vspace*{-8cm}% *)
(** %\setcounter{secnumdepth}{1}% *)
(** printing theta %\ensuremath{\theta}% #θ# *)
(** printing theta' %\ensuremath{\theta'}% #θ'# *)
(** printing theta'' %\ensuremath{\theta''}% #θ''# *)

(** printing rho %\ensuremath{\rho}% #ρ# *)
(** printing rho' %\ensuremath{\rho'}% #ρ'# *)
(** printing rho'' %\ensuremath{\rho''}% #ρ''# *)
(** printing rhos %\ensuremath{\vec{\rho}}% #ρs# *)
(** printing rhos' %\ensuremath{\vec{\rho'}}% #ρs'# *)
(** printing rhos'' %\ensuremath{\vec{\rho''}}% #ρs''# *)

(** printing sigma %\ensuremath{\sigma}% #σ#*)
(** printing sigmas %\ensuremath{\vec{\sigma}}% #σs#*)
(** printing sigmas0 %\ensuremath{\vec{\sigma_0}}% #σs0#*)

(** printing mu %\ensuremath{\mu}% #μ#*)
(** printing mus %\ensuremath{\vec{\mu}}% #μs#*)

(** printing tau %\ensuremath{\tau}% #τ# *)
(** printing tau' %\ensuremath{\tau'}% #τ'# *)
(** printing taus %\ensuremath{\vec{\tau}}% #τs# *)
(** printing taus' %\ensuremath{\vec{\tau'}}% #τs'# *)

(** printing o %\ensuremath{\circ}% *)
(** printing ||\ %\ensuremath{\Uparrow}% *)
(** printing |\ %\ensuremath{\uparrow}% *)
(** printing \ %\ensuremath{\lambda}% #λ# *)
(** printing \! %\ensuremath{\lambda}% #λ# *)
(** printing (\ %\ensuremath{(\lambda}% #(λ# *)
(** printing (\! %\ensuremath{(\lambda}% #(λ# *)
(** printing --> %\ensuremath{\mapsto}% *)
(** printing ---> %\ensuremath{\mapsto}% *)
(** printing )--> %\ensuremath{)\mapsto}% *)
(** printing )---> %\ensuremath{)\mapsto}% *)
(** printing -->( %\ensuremath{\mapsto(}% *)
(** printing --->( %\ensuremath{\mapsto(}% *)
(** printing ! %\ensuremath{^{nc}}% *)
(** printing !) %\ensuremath{^{nc})}% *)
(** printing )!) %\ensuremath{)^{nc})}% *)
(** printing forallnc %\ensuremath{\forall^{nc}}% *)
(** printing existsnc %\ensuremath{\existsnc^{nc}}% *)
(** printing letnc %\ensuremath{\coqdocid{let}^{nc}}% *)
